[workspace]
members = [ "icepick-backend", "cli", 
    "core", "engine-backend",
    "indexer", 
    "sort-results", "webui",
]

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
url = "2.5.4"
