[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
select = "0.6.0"
reqwest = "0.12.11"
tokio = { version = "1.42.0", features = ["full"] }
url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }