[serve]
# The address to serve on LAN.
addresses = [ "127.0.0.1" ]

# The address to serve on WAN.
# address = "0.0.0.0"

# The port to serve on.
port = 6727

[build]
# target = "wasm32-unknown-unknown"
dist = "dist"
static-dir = "static"